//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchange.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Currency", Namespace="http://schemas.datacontract.org/2004/07/CurrencyService")]
    public enum Currency : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dollar = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yen = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IExchangeRate")]
    public interface IExchangeRate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeRate/Rate", ReplyAction="http://tempuri.org/IExchangeRate/RateResponse")]
        double Rate(CurrencyExchange.ServiceReference1.Currency currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeRate/Rate", ReplyAction="http://tempuri.org/IExchangeRate/RateResponse")]
        System.Threading.Tasks.Task<double> RateAsync(CurrencyExchange.ServiceReference1.Currency currency);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExchangeRateChannel : CurrencyExchange.ServiceReference1.IExchangeRate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExchangeRateClient : System.ServiceModel.ClientBase<CurrencyExchange.ServiceReference1.IExchangeRate>, CurrencyExchange.ServiceReference1.IExchangeRate {
        
        public ExchangeRateClient() {
        }
        
        public ExchangeRateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExchangeRateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeRateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeRateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Rate(CurrencyExchange.ServiceReference1.Currency currency) {
            return base.Channel.Rate(currency);
        }
        
        public System.Threading.Tasks.Task<double> RateAsync(CurrencyExchange.ServiceReference1.Currency currency) {
            return base.Channel.RateAsync(currency);
        }
    }
}
